name: ci

on:
  push:
    branches:
      - 'master'
env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log in to Docker Hub
        run: echo $PASSWORD | docker login -u $USERNAME --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/personalapi:latest
