name: build docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Log in to Docker Hub
        run: |
          echo "dckr_pat_DLXc2d5nhoqg6unXxTcHWvXUP5w" | docker login -u Farmeurimmo --password-stdin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/personalapi:latest
